### ISSUE TITLE
compile issue on Ubunut 20.04

### ISSUE THREAD

**Issue by schoeberl** [leros-dev/leros-llvm#2]
Maybe I am missing some packages, but on my Ubuntu I am also not very lucky:

```
[ 87%] Building CXX object tools/leros-clang/lib/StaticAnalyzer/Checkers/CMakeFiles/clangStaticAnalyzerCheckers.dir/NSErrorChecker.cpp.o
/home/martin/leros-dev/leros-llvm/tools/leros-clang/lib/StaticAnalyzer/Core/Z3ConstraintManager.cpp: In function ‘void {anonymous}::Z3ErrorHandler(Z3_context, Z3_error_code)’:
/home/martin/leros-dev/leros-llvm/tools/leros-clang/lib/StaticAnalyzer/Core/Z3ConstraintManager.cpp:49:40: error: ‘Z3_get_error_msg_ex’ was not declared in this scope; did you mean ‘Z3_get_error_msg’?
   49 |                            llvm::Twine(Z3_get_error_msg_ex(Context, Error)));
      |                                        ^~~~~~~~~~~~~~~~~~~
      |                                         ^~~~~~~~~~~~~~~~~~~
```

**Comment by mortbopet** [comment]
Looks like we are running into the samme issues as faced here: https://reviews.llvm.org/D54391
It might be that earlier ubuntu versions still had the development headers for the (deprecated) Z3 version so we didn't encounter this issue back then.
No matter what, this should be fixable by either fetching an older version of Z3 or syncing Leros-LLVM with upstream LLVM.

**Comment by mortbopet** [comment]
7e4ffd0755a79203c56b3b14cbbe358b23ed3d83 should fix the issue. Compiles successfully for me now, on ubuntu 20.04.

**Comment by schoeberl** [comment]
Yes, that fixed it. Thank's for the quick help.
